config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  root "page#first"
  get "page/second", to: "page#second"
  resources :articles
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ActiveRecord::Base 
    puts "this is model class calling 0000000000000000000000000000000000000"
    validates :title, presence: true, length: {minimum:3, maximum:50}
        validates :description,presence: true ,length: {minimum:3, maximum:100}
end

app/models/user.rb
Class User < ActiveRecord::Base

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ActionController::Base
    before_action :find_article, only: [:show, :edit]
    def index
        @articles = Article.all
        puts "in index page 000000000000000000000000000000000"
    end
    
    def new
        @article = Article.new
        puts "in def new method 00000000000000000000000000000000000000000000000000"    

    end
    def create
       
        #render plain: params[:article].inspect
        @article = Article.new (article_params)
        if @article.save
            flash[:notice] = "Article was successfully saved"
            
            puts "in create method 000000000000000000000000000000000"
            redirect_to articles_path
                    else
            render "new"
        end
    end
    def show 
                
    end

    def edit
        puts "IN def edit method 00000000000000000000000000 "
    end
    def update

        puts "in def update method 000000000000000000000000000"
        @article = Article.new(article_params)
        if @article.save
            redirect_to new_article_path
        
        else
            render "edit"
        end
    end
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end


    
    private 
    def find_article
        @article = Article.find(params[:id])
    end

    def article_params
        puts "in article params method 000000000000000000000000000000000"
        params.require(:article).permit(:title,:description)
    end
    
end

app/controllers/pages_controller.rb
class PageController < ApplicationController

    def first
    @article = Article.new(params[:id])
    
    end
    
    def second

    end
            
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>
<% if @article.errors.any? %>
<ul>
    <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
</ul>
    <% end %>
<% end %>
<% @article.inspect    %>
<%=  form_for @article do |f| %>
   <p> 
   <%= f.label :title %>
   <%= f.text_field :title %>
   </p>   
   <p>
    <%= f.label  "description" %><br>
    <%= f.text_area :description %>
   </p>
   <%= f.submit "Edit Article" %>
    
    
<% end %>
  <%= link_to "Show All Articles", articles_path %>

app/views/articles/index.html.erb
<h1> Showing all articles</h1>
<p>
    <%= link_to "Create New Article", new_article_path %>
</p>
<table>
    <tr>
        <th>Title</th>
        <th>Description</th>       
    </tr>

    <% @articles.each do |article|%>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Edit Article', edit_article_path(article) %></td>
        <td><%= link_to 'Show Article', article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm:"are you sure"} %> </td>

    </tr>
    <% end %>

</table>
<%= link_to "Create new article", new_article_path %>

app/views/articles/new.html.erb
<p>Create an article</p>
<% if @article.errors.any? %>
<h2>The following errors prevented article from getting created </h2>
    <ul>
  <% @article.errors.full_messages.each do |error| %>
    
    <li> <%= error %></li>
    
    <% end %>
    </ul>
<% end %>

<%= form_for @article do |f| %>
    <p>
        <%= f.label :title %>
        <br>
        <%= f.text_field  :title %><br>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
        <p>
        <%= f.submit %>
        <p>
     <p>
               


    <% end %>
    <%= link_to "Show All Articles", articles_path %>
     

app/views/articles/show.html.erb
<p> This is Show page</p>
         

<p> Title: <%= @article.title %></p>
<p> Description: <%= @article.description %></p>
<%= link_to "Edit This Article", edit_article_path(@article) %>
<%= link_to "Show All Articles", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  

  <h1> hellloooooooooooooooooooo</h1>

    <%= yield %>
  </body>
</html>

app/views/page/first.html.erb
<p>hi this is first page</p>
<%= link_to "jump to welcome page", page_second_path %>


      <%=   @article.inspect %>   

app/views/page/second.html.erb
<p> Hello .this is welcome page<p>
<%= link_to "jump to first page", root_path %>